# Generated by Django 3.1.7 on 2021-03-17 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('model', models.FileField(upload_to='models/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(upload_to='uploads/')),
                ('output', models.FileField(blank=True, upload_to='results/')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.version')),
            ],
        ),
    ]
